FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

ADD . /repo
WORKDIR /repo/examples/cmdline
RUN cc main.c ../../elk.c -I../.. -o cli -lm
